Added ecs-anywhere role and anisble-galaxy collection files
gaggle-net/ansible-collection-ecs-anywhere pull request #1
Opened 2021-08-11 18:55 UTC by sergio-gaggle

Added ecs-anywhere role and tasks files. Also added manifest file for ansible-galaxy collection packaging.

2021-08-11 22:31 UTC, cplee requested changes
Can we make `aws_profile` optional? We use profiles a lot internally, but that isn't the best assumption for others...some may not use profiles the way we do.

Also, there is a lot of dependency on the AWS CLI - any reason why we couldn't use Ansible plugins and write the code in Python using boto3 to remove the need for the AWS CLI?

2021-08-11 22:31 UTC, cplee commented on MANIFEST.json
> +  "license_file": "LICENSE",
`LICENSE` file is missing - please add an MIT license file to the repo

2021-08-11 22:31 UTC, cplee commented on galaxy.yml
> +- GPL-2.0-or-later
no GPL please...let's use MIT

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/meta/main.yml
> +  license: Apache-2.0
change to MIT license for consistency

2021-08-11 22:31 UTC, cplee commented on README.md
> +## Running the Playbook
Would be good to document the parameters that are `required` and `optional`

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/tasks/main.yml
> +    url: https://amazon-ecs-agent-packages-preview.s3.us-east-1.amazonaws.com/ecs-anywhere-install.sh
the bucket name should come from `aws_bucket_name` parameter. Also, shouldn't use `preview` anymore as per: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere-registration.html

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/defaults/main.yml
> +aws_s3_bucket: amazon-ecs-agent-packages-preview
shouldn't use `preview` anymore as per: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere-registration.html

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/tasks/main.yml
> +  local_action: ansible.builtin.command /usr/bin/aws ssm create-activation --iam-role {{ aws_ssm_role }} --registration-limit {{ ansible_play_hosts | length }} --profile {{ aws_profile }}
`create-activation` is called in 3 separate places - can this be simplified?

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/tasks/register-ssm-instance.yml
> +  local_action: ansible.builtin.command /usr/bin/aws ssm create-activation --iam-role {{ aws_ssm_role }} --registration-limit {{ ansible_play_hosts | length }} --profile {{ aws_profile }}
`create-activation` is called in 3 separate places - can this be simplified?

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/tasks/aws-script-install.yml
> +  local_action: ansible.builtin.command /usr/bin/aws ssm create-activation --iam-role {{ ssm_role }} --registration-limit {{ ansible_play_hosts | length }} --profile {{ aws_profile }}
`create-activation` is called in 3 separate places - can this be simplified?

2021-08-11 22:31 UTC, cplee commented on roles/ecs_anywhere/tasks/aws-script-install.yml
> +    checksum: sha256:https://amazon-ecs-agent-packages-preview.s3.us-east-1.amazonaws.com/ecs-anywhere-install.sh.sha256
these are the old buckets from preview: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere-registration.html

2021-09-08 01:21 UTC, sergio-gaggle commented on MANIFEST.json
> +  "license_file": "LICENSE",
Added MIT license file and wrote modules to remove dependency on the AWS CLI. aws_ssm_activation module creates/gets/deletes SSM activations and aws_ssm_instance module gets/de-registers instances from SSM

2021-09-08 01:21 UTC, sergio-gaggle commented on galaxy.yml
> +- GPL-2.0-or-later
Updated to MIT

2021-09-08 01:21 UTC, sergio-gaggle commented on roles/ecs_anywhere/meta/main.yml
> +  license: Apache-2.0
Updated to MIT

2021-09-08 16:02 UTC, cplee commented
@sergio-gaggle - this is looking REALLY good 🤩

Only 1 last request before we merge it - can you update the `README.md` to include a list of vars like:

| variable | description | required? | default |
| -------- | ----------- | ---------- | ------- | 
| iam_role | Which IAM role to associate with instance | yes | - |
| aws_ecs_cluster | Name of ECS cluster to use | yes | - |
| aws_region | Which region to use for this ECS instance | no | `us-west-2` |
| aws_install_dir | Where to install ECS anywhere | no | `/opt/amazon/ecs-anywhere` |
| aws_script_url | Location of install script | no | `https://amazon-ecs-agent.s3.amazonaws.com/ecs-anywhere-install-latest.sh` |

2021-09-10 21:07 UTC, tmz-gaggle commented
Nice work putting this together Sergio!

Is Fedora really a supported OS for the collection?  ECS Anywhere itself says versions 32 and 33 are supported, which means they're  a month or two away from not supporting any current Fedora releases.  Fedora 32 was EOL in May.  Fedora 33 will be EOL 4 weeks after Fedora 35 is released, which is scheduled for October 19 or 26.  The versions in the collection here are 27 and 28, which have been EOL since November 2018 and May 2019, respectively.

It might be worth removing Fedora entirely unless we want to test it on Fedora 33 and update the README and role metadata?

Not the most useful of reviews, I know.  I just noticed those old versions in the README and thought I'd ask.

2021-09-13 17:19 UTC, sergio-gaggle commented on README.md
> +## Running the Playbook
Added section to README describing which variables are optional or required.

2021-09-13 17:23 UTC, cplee approved these changes

2021-09-13 19:52 UTC, cplee commented
@sergio-gaggle - ready to merge?

2021-09-13 23:27 UTC, sergio-gaggle commented
@cplee yup, ready to merge to master

2021-09-14 00:16 UTC, merged